/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ipn.mx.practica01;


import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author EMend17
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCifrar = new javax.swing.JButton();
        buttonDeifrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        keyField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica 01: DES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        buttonCifrar.setText("Cifrar un mensaje");
        buttonCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCifrarActionPerformed(evt);
            }
        });

        buttonDeifrar.setText("Decifrar un mensaje");
        buttonDeifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeifrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresa la llave: ");

        keyField.setDoubleBuffered(true);
        keyField.setDragEnabled(true);
        keyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDeifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCifrarActionPerformed
        fileHandler fh = new fileHandler();
        DES des = new DES();
        //Recibe la llave proporcionada por el usuario, si no hay se usa la default
        String llave =  new String(keyField.getPassword());
        if (!llave.isEmpty()) {
            des.KEY = llave;
        }
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files(*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        
        //Cambiar la ruta que abre el explorador de archivos por default
        File ruta = new File("D:\\Documentos\\7to semestre\\CRYPTOGRAPHY\\Practicas\\Practica1");
        fileChooser.setCurrentDirectory(ruta);
        int result = fileChooser.showOpenDialog(this);

        String path = fileChooser.getSelectedFile().getAbsolutePath();

        String contenido = null;
        try {
            contenido = fh.readFile(path);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        String newPath = fh.modFileName(path, 'C');

        String contenidoCifrado = des.crypt(contenido);

        try {
            fh.writeFile(newPath, contenidoCifrado);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
//        System.out.print(path);
//        System.out.print("\n " + contenido);
//        System.out.print("\n " + newPath);

    }//GEN-LAST:event_buttonCifrarActionPerformed

    private void buttonDeifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeifrarActionPerformed
        fileHandler fh = new fileHandler();
        DES des = new DES();
        //Recibe la llave proporcionada por el usuario, si no hay se usa la default
        String llave =  new String(keyField.getPassword());
        if (!llave.isEmpty()) {
            des.KEY = llave;
        }
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files(*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        //Cambiar la ruta que abre el explorador de archivos por default
        File ruta = new File("D:\\Documentos\\7to semestre\\CRYPTOGRAPHY\\Practicas\\Practica1");
        fileChooser.setCurrentDirectory(ruta);
        int result = fileChooser.showOpenDialog(this);

        String path = fileChooser.getSelectedFile().getAbsolutePath();

        String contenido = null;
        try {
            contenido = fh.readFile(path);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        String newPath = fh.modFileName(path, 'D');

        String contenidoDecifrado = des.decrypt(contenido);

        try {
            fh.writeFile(newPath, contenidoDecifrado);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
//        System.out.print(path);
//        System.out.print("\n " + contenido);
//        System.out.print("\n " + newPath);
    }//GEN-LAST:event_buttonDeifrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon("C:\\Users\\emili\\Documents\\7to semestre\\Crypto\\Practicas\\Practica1\\src\\res\\icon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void keyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyFieldActionPerformed
        keyField.setEchoChar((char)0);
    }//GEN-LAST:event_keyFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCifrar;
    private javax.swing.JButton buttonDeifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField keyField;
    // End of variables declaration//GEN-END:variables

}
